import React, { useState, useEffect } from 'react';
import { Button, Panel, PanelTitle } from './ui';

interface Scenario {
  id: string;
  title: string;
  description: string;
  severity: 'breaking' | 'warning' | 'info';
  type: string;
  impact: string;
  fix: string;
  changes?: Array<{
    field: string;
    change: string;
    type: 'breaking' | 'warning' | 'info';
  }>;
}

const scenarios: Scenario[] = [
  {
    id: 'header-addition',
    title: 'Added Header: X-API-Version',
    description: 'Adding a version header helps clients identify the API version they are consuming.',
    severity: 'info',
    type: 'REST',
    impact: 'Low - Clients can optionally use the version header',
    fix: 'Document the header usage and maintain backward compatibility',
    changes: [
      { field: 'Response header', change: 'X-API-Version → added', type: 'info' }
    ]
  },
  {
    id: 'field-type-change',
    title: 'Changed Field Type: count from integer to string',
    description: 'Changing the count field from integer to string breaks clients expecting numeric values.',
    severity: 'breaking',
    type: 'REST',
    impact: 'High - Clients parsing count as integer will fail',
    fix: 'Use a new field name (e.g., count_str) or keep both fields during transition',
    changes: [
      { field: 'Response body.count', change: 'integer → string', type: 'breaking' }
    ]
  },
  {
    id: 'header-removal',
    title: 'Removed Header: X-RateLimit-Remaining',
    description: 'Removing a custom rate limit header breaks clients that monitor their API usage.',
    severity: 'warning',
    type: 'REST',
    impact: 'Medium - Clients lose visibility into rate limiting',
    fix: 'Provide alternative header or keep deprecated header for transition period',
    changes: [
      { field: 'Response header', change: 'X-RateLimit-Remaining → removed', type: 'warning' }
    ]
  }
];

/* The three change severities a scenario carries, and the §4 badge each one
   gets. §2 keeps the colours exclusive — teal healthy, amber warning, red
   breaking, sky info — and §4 carries the same distinction in shape, so the
   badge still reads for someone who cannot tell Fault Red from Vital Teal. */
const SEVERITY: Record<
  'breaking' | 'warning' | 'info',
  { badge: string; shape: string; label: string }
> = {
  breaking: { badge: 'badge-breaking', shape: '■', label: 'BREAKING' },
  warning: { badge: 'badge-warning', shape: '▲', label: 'WARNING' },
  info: { badge: 'badge-info', shape: '●', label: 'INFO' },
};

/* Built from an array rather than written out four times: the four copies had
   already drifted, two of them carrying a stray `active` class the other two
   did not, and the `info` one tinted itself teal so it was indistinguishable
   from `all` when both were unselected. */
const FILTERS = [
  { id: 'all', label: 'All Scenarios' },
  { id: 'breaking', label: 'Breaking' },
  { id: 'warning', label: 'Warnings' },
  { id: 'info', label: 'Informational' },
];

const ScenarioLibrary: React.FC = () => {
  const [activeFilter, setActiveFilter] = useState<string>('all');
  const [activeScenario, setActiveScenario] = useState<Scenario | null>(null);

  const filteredScenarios = activeFilter === 'all'
    ? scenarios
    : scenarios.filter(s => s.severity === activeFilter);

  useEffect(() => {
    const handleShowScenario = () => {
      const root = document.getElementById('scenario-react-root');
      if (root) {
        (root as HTMLElement).style.display = 'block';
      }
    };
    window.addEventListener('showScenario', handleShowScenario);
    return () => {
      window.removeEventListener('showScenario', handleShowScenario);
    };
  }, []);

  /* §4's status badge: pill, 1px tinted border at 30%, fill at 15%. The shell
     already implements exactly that as .contract-badge + .badge-*, so this
     reuses it rather than restating the values — the shell and the React views
     ship one stylesheet, and two definitions of the same badge is how they end
     up disagreeing.

     What stood here was a 32px square with the whole word inside it, and the
     colour came from `text-${textColor}`. Both halves were broken. "BREAKING"
     measures 81px inside a 32px box, so all three badges spilled out of their
     own background. And the interpolated class name only resolved because other
     files happened to contain the same literal — Tailwind's scanner cannot see
     a name assembled at runtime, so the colour that worked was really being
     generated by an unrelated file, and would have disappeared the first time
     that file was tidied. */
  const renderSeverityBadge = (severity: 'breaking' | 'warning' | 'info') => {
    const { badge, shape, label } = SEVERITY[severity];
    return (
      <span className={`contract-badge ${badge}`}>
        <span aria-hidden="true">{shape}</span>
        {label}
      </span>
    );
  };

  // Handle active scenario view
  if (activeScenario) {
    return (
      <div className="space-y-8">
        <div className="text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-text-main mb-4">Scenario Library</h2>
          <p className="text-text-muted max-w-xl mx-auto">
            Learn about API contract changes with pre-configured breaking change scenarios
          </p>
        </div>

        <Panel>
          <div className="flex justify-between items-start mb-4">
            <div className="flex items-center space-x-3">
              {renderSeverityBadge(activeScenario.severity)}
              <div>
                <PanelTitle className="mb-1">
                  {activeScenario.title}
                </PanelTitle>
                <p className="text-sm text-text-muted">{activeScenario.type}</p>
              </div>
            </div>
            <Button size="sm" onClick={() => {
                setActiveScenario(null);
                const scenarioRoot = document.getElementById('scenario-react-root');
                if (scenarioRoot) (scenarioRoot as HTMLElement).style.display = 'none';
                const webhookRoot = document.getElementById('webhook-react-root');
                if (webhookRoot) (webhookRoot as HTMLElement).style.display = 'none';
                document.getElementById('view-traffic')!.classList.add('active');
                document.querySelectorAll('.nav-item').forEach(el => el.classList.remove('active'));
                document.getElementById('nav-traffic')!.classList.add('active');
              }}>
              Back to Scenarios
            </Button>
          </div>

          <div className="space-y-4">
            <p className="text-base text-text-muted">{activeScenario.description}</p>

            <div className="gap-4">
              <div>
                <PanelTitle level={4} size="base" className="mb-2">Impact</PanelTitle>
                <p className="text-base text-text-muted">{activeScenario.impact}</p>
              </div>
              <div>
                <PanelTitle level={4} size="base" className="mb-2">Type</PanelTitle>
                <p className="text-base text-text-muted">{activeScenario.type}</p>
              </div>
            </div>

            {activeScenario.changes && activeScenario.changes.length > 0 ? (
              <div className="mt-4">
                <PanelTitle level={4} size="base" className="mb-2">Changes</PanelTitle>
                <div className="space-y-2">
                  {activeScenario.changes.map((change, index) => (
                    <div key={index} className="bg-bg-hover rounded-lg p-3">
                      <div className="flex justify-between">
                        <span className="text-sm font-medium text-text-muted">Changes:</span>
                        <span className="font-mono text-text-main">{change.change}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : null}

            <div className="mt-4">
              <PanelTitle level={4} size="base" className="mb-2">Fix</PanelTitle>
              <p className="text-base text-text-muted">{activeScenario.fix}</p>
            </div>
          </div>
        </Panel>
      </div>
    );
  }

  // Handle scenario grid view
  return (
    <div className="space-y-8">
      <div className="text-center">
        <h2 className="text-2xl font-semibold tracking-tight text-text-main mb-4">Scenario Library</h2>
        <p className="text-text-muted max-w-xl mx-auto">
          Learn about API contract changes with pre-configured breaking change scenarios
        </p>
      </div>

      {/* Filters */}
      <Panel>
        <div className="flex flex-wrap gap-2">
          {FILTERS.map((f) => (
            <Button
              key={f.id}
              size="md"
              variant={activeFilter === f.id ? 'primary' : 'secondary'}
              aria-pressed={activeFilter === f.id}
              onClick={() => setActiveFilter(f.id)}
            >
              {f.label}
            </Button>
          ))}
        </div>
      </Panel>

      {/* Scenarios Grid */}
      <div className="grid gap-6">
        {filteredScenarios.map(scenario => (
          <Panel key={scenario.id}>
            <div className="flex justify-between items-start mb-4">
              <div className="flex items-center space-x-3">
                {renderSeverityBadge(scenario.severity)}
                <div>
                  <PanelTitle className="mb-1">
                    {scenario.title}
                  </PanelTitle>
                  <p className="text-sm text-text-muted">{scenario.type}</p>
                </div>
              </div>

              <Button size="sm" onClick={() => setActiveScenario(scenario)}>
                View Details
              </Button>
            </div>

            <div className="space-y-4">
              <p className="text-base text-text-muted">{scenario.description}</p>

              <div className="grid gap-4">
                <div>
                  <PanelTitle level={4} size="base" className="mb-2">Impact</PanelTitle>
                  <p className="text-base text-text-muted">{scenario.impact}</p>
                </div>
                <div>
                  <PanelTitle level={4} size="base" className="mb-2">Type</PanelTitle>
                  <p className="text-base text-text-muted">{scenario.type}</p>
                </div>
              </div>

              {scenario.changes && scenario.changes.length > 0 ? (
                <div className="mt-4">
                  <PanelTitle level={4} size="base" className="mb-2">Changes</PanelTitle>
                  <div className="space-y-2">
                    {scenario.changes.map((change, index) => (
                      <div key={index} className="bg-bg-hover rounded-lg p-3">
                        <div className="flex justify-between">
                          <span className="text-sm font-medium text-text-muted">Changes:</span>
                          <span className="font-mono text-text-main">{change.change}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          </Panel>
        ))}
      </div>
    </div>
  );
};

export default ScenarioLibrary;