package contract

import (
	"fmt"
	"sort"
	"strings"

	"github.com/donaina/driftwood/pkg/types"
)

// TypeScriptKeywords are reserved words that must be quoted as identifiers
var TypeScriptKeywords = map[string]bool{
	"abstract": true, "arguments": true, "await": true, "boolean": true,
	"break": true, "byte": true, "case": true, "catch": true,
	"char": true, "class": true, "const": true, "continue": true,
	"debugger": true, "default": true, "delete": true, "do": true,
	"double": true, "else": true, "enum": true, "eval": true,
	"export": true, "extends": true, "false": true, "final": true,
	"finally": true, "float": true, "for": true, "function": true,
	"goto": true, "if": true, "implements": true, "import": true,
	"in": true, "instanceof": true, "int": true, "interface": true,
	"let": true, "long": true, "native": true, "new": true,
	"null": true, "package": true, "private": true, "protected": true,
	"public": true, "return": true, "short": true, "static": true,
	"super": true, "switch": true, "synchronized": true, "this": true,
	"throw": true, "throws": true, "transient": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true,
	"volatile": true, "while": true, "with": true, "yield": true,
	// Strict mode reserved
	"as": true, "async": true, "from": true, "get": true, "of": true,
	"set": true, "meta": true, "target": true,
	// Need explicit "type" too
	"type": true,
}

func isValidTSIdentifier(s string) bool {
	if s == "" {
		return false
	}
	if TypeScriptKeywords[s] {
		return false
	}
	first := s[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_' || first == '$') {
		return false
	}
	for i := 1; i < len(s); i++ {
		c := s[i]
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '$') {
			return false
		}
	}
	return true
}

func quoteTSIdentifier(s string) string {
	if isValidTSIdentifier(s) {
		return s
	}
	return "`" + s + "`"
}

func pascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r != '_' && r != '$' && (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9')
	})
	var result strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		result.WriteString(strings.Title(strings.ToLower(p)))
	}
	if result.Len() == 0 {
		result.WriteString("Type")
	}
	return result.String()
}

// GenerateTypeScriptInterfaces converts an inferred JSON schema into TypeScript interface definitions
func GenerateTypeScriptInterfaces(interfaceName string, node *types.JSONSchemaNode) string {
	if node == nil {
		return fmt.Sprintf("// Auto-generated by Driftwood for interface %s\nexport type %s = any;\n", interfaceName, interfaceName)
	}

	// Collect all nested types that need separate interfaces
	nestedTypes := make(map[string]*types.JSONSchemaNode)
	collectNestedTypes(node, nestedTypes, "")

	// Sort nested type names for deterministic output
	var nestedNames []string
	for name := range nestedTypes {
		nestedNames = append(nestedNames, name)
	}
	sort.Strings(nestedNames)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Auto-generated by Driftwood for interface %s\n", interfaceName))

	// Generate nested interfaces first
	for _, nestedName := range nestedNames {
		buildTypeInterface(&sb, nestedName, nestedTypes[nestedName], 0, nestedTypes)
		sb.WriteString("\n")
	}

	// Generate main interface
	buildTypeInterface(&sb, interfaceName, node, 0, nestedTypes)

	return sb.String()
}

func collectNestedTypes(node *types.JSONSchemaNode, nestedTypes map[string]*types.JSONSchemaNode, parentPrefix string) {
	if node == nil || node.Type != types.TypeObject {
		return
	}

	for key, prop := range node.Properties {
		if prop.Type == types.TypeObject {
			nestedName := parentPrefix + pascalCase(key)
			if nestedName == "" {
				nestedName = "Nested"
			}
			nestedTypes[nestedName] = prop
			collectNestedTypes(prop, nestedTypes, nestedName)
		}
		if prop.Type == types.TypeArray && prop.ItemSchema != nil && prop.ItemSchema.Type == types.TypeObject {
			itemName := parentPrefix + pascalCase(key) + "Item"
			if itemName == "" {
				itemName = "Item"
			}
			nestedTypes[itemName] = prop.ItemSchema
			collectNestedTypes(prop.ItemSchema, nestedTypes, itemName)
		}
	}
}

func buildTypeInterface(sb *strings.Builder, name string, node *types.JSONSchemaNode, indentLevel int, nestedTypes map[string]*types.JSONSchemaNode) {
	indent := strings.Repeat("  ", indentLevel)

	switch node.Type {
	case types.TypeObject:
		sb.WriteString(fmt.Sprintf("%sexport interface %s {\n", indent, name))

		keys := make([]string, 0, len(node.Properties))
		for k := range node.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			propNode := node.Properties[k]
			optFlag := ""
			if propNode.Nullable && propNode.Type != types.TypeNull {
				optFlag = "?"
			}

			tsType := getTypeString(propNode, k, nestedTypes)
			quotedKey := quoteTSIdentifier(k)
			sb.WriteString(fmt.Sprintf("%s  %s%s: %s;\n", indent, quotedKey, optFlag, tsType))
		}

		sb.WriteString(fmt.Sprintf("%s}\n", indent))

	case types.TypeArray:
		itemType := "any"
		if node.ItemSchema != nil {
			itemType = getTypeString(node.ItemSchema, "item", nestedTypes)
		}
		sb.WriteString(fmt.Sprintf("%sexport type %s = %s[];\n", indent, name, itemType))

	default:
		tsType := getTypeString(node, name, nestedTypes)
		sb.WriteString(fmt.Sprintf("%sexport type %s = %s;\n", indent, name, tsType))
	}
}

func getTypeString(node *types.JSONSchemaNode, keyHint string, nestedTypes map[string]*types.JSONSchemaNode) string {
	if node == nil {
		return "any"
	}

	switch node.Type {
	case types.TypeString:
		return "string"
	case types.TypeInteger, types.TypeNumber:
		return "number"
	case types.TypeBoolean:
		return "boolean"
	case types.TypeNull:
		return "null"
	case types.TypeArray:
		item := "any"
		if node.ItemSchema != nil {
			item = getTypeString(node.ItemSchema, "item", nestedTypes)
		}
		return fmt.Sprintf("%s[]", item)
	case types.TypeObject:
		if len(node.Properties) == 0 {
			return "Record<string, any>"
		}

		// Check if this object is one of our nested types
		for nestedName, nestedNode := range nestedTypes {
			if nestedNode == node {
				return nestedName
			}
		}

		// Inline object for small/anonymous objects
		keys := make([]string, 0, len(node.Properties))
		for k := range node.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var fields []string
		for _, k := range keys {
			prop := node.Properties[k]
			opt := ""
			if prop.Nullable {
				opt = "?"
			}
			fields = append(fields, fmt.Sprintf("%s%s: %s", quoteTSIdentifier(k), opt, getTypeString(prop, k, nestedTypes)))
		}
		return fmt.Sprintf("{ %s }", strings.Join(fields, "; "))
	default:
		return "any"
	}
}