package contract

import (
	"fmt"
	"sort"
	"strings"

	"github.com/callmidavid/apidiff/pkg/types"
)

// GenerateTypeScriptInterfaces converts an inferred JSON schema into TypeScript interface definitions
func GenerateTypeScriptInterfaces(interfaceName string, node *types.JSONSchemaNode) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Auto-generated by APIDiff for interface %s\n", interfaceName))

	if node == nil {
		sb.WriteString(fmt.Sprintf("export type %s = any;\n", interfaceName))
		return sb.String()
	}

	buildType(&sb, interfaceName, node, 0)
	return sb.String()
}

func buildType(sb *strings.Builder, name string, node *types.JSONSchemaNode, indentLevel int) {
	indent := strings.Repeat("  ", indentLevel)

	switch node.Type {
	case types.TypeObject:
		sb.WriteString(fmt.Sprintf("%sexport interface %s {\n", indent, name))

		// Sort keys for deterministic output
		keys := make([]string, 0, len(node.Properties))
		for k := range node.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			propNode := node.Properties[k]
			optFlag := ""
			if propNode.Nullable {
				optFlag = "?"
			}

			tsType := getNodeTSType(propNode)
			sb.WriteString(fmt.Sprintf("%s  %s%s: %s;\n", indent, k, optFlag, tsType))
		}

		sb.WriteString(fmt.Sprintf("%s}\n", indent))

	case types.TypeArray:
		itemType := "any"
		if node.ItemSchema != nil {
			itemType = getNodeTSType(node.ItemSchema)
		}
		sb.WriteString(fmt.Sprintf("%sexport type %s = %s[];\n", indent, name, itemType))

	default:
		tsType := getNodeTSType(node)
		sb.WriteString(fmt.Sprintf("%sexport type %s = %s;\n", indent, name, tsType))
	}
}

func getNodeTSType(node *types.JSONSchemaNode) string {
	if node == nil {
		return "any"
	}

	var base string
	switch node.Type {
	case types.TypeString:
		base = "string"
	case types.TypeInteger, types.TypeNumber:
		base = "number"
	case types.TypeBoolean:
		base = "boolean"
	case types.TypeNull:
		base = "null"
	case types.TypeArray:
		item := "any"
		if node.ItemSchema != nil {
			item = getNodeTSType(node.ItemSchema)
		}
		base = fmt.Sprintf("%s[]", item)
	case types.TypeObject:
		if len(node.Properties) == 0 {
			base = "Record<string, any>"
		} else {
			var fields []string
			keys := make([]string, 0, len(node.Properties))
			for k := range node.Properties {
				keys = append(keys, k)
			}
			sort.Strings(keys)

			for _, k := range keys {
				prop := node.Properties[k]
				opt := ""
				if prop.Nullable {
					opt = "?"
				}
				fields = append(fields, fmt.Sprintf("%s%s: %s", k, opt, getNodeTSType(prop)))
			}
			base = fmt.Sprintf("{ %s }", strings.Join(fields, "; "))
		}
	default:
		base = "any"
	}

	if node.Nullable && node.Type != types.TypeNull {
		return fmt.Sprintf("%s | null", base)
	}
	return base
}
